---
- name: Install postgres
  apt:
    name:
      - "postgresql-{{postgresql_version}}"
      - "postgresql-client-{{postgresql_version}}"
      - "postgresql-contrib-{{postgresql_version}}"
    state: present
    update-cache: yes
    cache_valid_time: 43200

- name: Install python2 psycopg2
  pip:
    name: "psycopg2"
    executable: "pip2"

- name: Install postgres_hba configuration file.
  template: src=files/conf/pg_hba.conf dest=/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf

- name: Configure Postgres
  lineinfile:
    dest: /etc/postgresql/{{postgresql_version}}/main/postgresql.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "effective_cache_size = 256MB"
    - "maintenance_work_mem = 256MB"
    - "shared_buffers = 128MB"
    - "work_mem = 100MB"

- name: restart postgres
  service: name=postgresql state=restarted

- name: Create user.
  postgresql_user:
    name: "{{project_name}}"
    role_attr_flags: "CREATEDB,SUPERUSER"

- name: Create database.
  postgresql_db:
    name: "{{project_name}}"

