---
- name: Install postgres
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
    cache_valid_time: 43200
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"

- name: Install python2 psycopg2
  pip:
    name: "psycopg2"
    executable: "pip2"

- name: Install postgres_hba configuration file.
  template: src=files/conf/pg_hba.conf dest=/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf

- name: Install postgresql.conf
  template:
    src: files/conf/postgresql.conf
    dest: "/etc/postgresql/{{postgresql_version}}/main/postgresql.conf"

- name: restart postgres
  service: name=postgresql state=restarted

- name: Create user.
  postgresql_user:
    name: "{{project_name}}"
    role_attr_flags: "CREATEDB,SUPERUSER"

- name: Create database.
  postgresql_db:
    name: "{{project_name}}"

