---
- hosts: all
  vars_files:
    - vars.yml
    # - @vault.yml
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"
  tasks:

    - cronvar:
        name: MAILTO
        value: "{{ cron_email|format(ec2_tag_Name|default('wcivf')) }}"
        user: "{{ project_name }}"

    - name: "Process log queue"
      cron:
        name: "Process log queue"
        job: "{{ project_name }}_cron_cmd process_log_queue"

    - name: "Import Ballot"
      cron:
        name: "Import Ballots"
        minute: "50"
        hour: "2"
        job: "/usr/local/bin/lockrun --lockfile=/tmp/ballots_and_people -W -- {{ project_name }}_cron_cmd import_ballots"
        disabled: no

    - name: "Import current Ballot"
      cron:
        name: "Import current Ballots"
        minute: "35"
        hour: "*/2"
        job: "/usr/local/bin/lockrun --lockfile=/tmp/ballots_and_people -W -- {{ project_name }}_cron_cmd import_ballots --current"
        disabled: yes

    - name: "Import Parties"
      cron:
        name: "Import Parties"
        minute: "10"
        hour: "2"
        job: "{{ project_name }}_cron_cmd import_parties"
        disabled: no

    - name: "Import Votes Cast"
      cron:
        minute: "*/5"
        name: "Import Votes Cast"
        job: "/usr/local/bin/lockrun --lockfile=/tmp/import_votes_cast -W -- {{ project_name }}_cron_cmd import_votes_cast --since=2021-05-05"
        disabled: no

    - name: "Import Referendums"
      cron:
        hour: "12"
        name: "Import Referendums"
        job: "/usr/local/bin/lockrun --lockfile=/tmp/import_referendums -W -- {{ project_name }}_cron_cmd import_referendums"
        disabled: no

    # Reboot jobs
    - name: Init data on restart
      cron:
        name: "Init data on reboot"
        special_time: reboot
        job: "sleep 30s && {{ project_root }}/load_database_from_s3.sh && {{ project_name }}_cron_cmd migrate --noinput && {{ project_name }}_cron_cmd init_data"

    # Controller jobs
    - name: Back up data to S3
      cron:
        name: "Back up data"
        minute: 16
        job: "/usr/local/bin/instance-tags 'Env=prod' && /usr/local/bin/instance-tags 'controller=True' && output-on-error {{ project_root }}/backup_db_to_s3.sh"

    - name: Init full data at 3.20
      cron:
        name: "Init data every hour"
        minute: 20
        hour: 3
        job: "/usr/local/bin/instance-tags 'controller=True' && {{ project_name }}_cron_cmd init_data --full"
        disabled: no
