---
  - name: Install required system packages.
    apt:
      name: "{{ system_packages }}"
      state: present
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: safe
      update-cache: yes
      cache_valid_time: 43200

  - name: Install required Python packages.
    pip:
      name: "{{ python_packages }}"
      executable: pip3

  # Install s3 with pip as a python 2 dependency because
  # apt installs it with python 3 and we hit this bug:
  # https://github.com/s3tools/s3cmd/issues/930
  # because we want to authenticate using iam role instead of key
  - name: Install s3cmd
    pip:
      name: s3cmd
      executable: pip2
    become: true
    become_user: root

  - name: Install .s3cfg file
    template:
      src: "files/conf/s3cfg"
      dest: /root/.s3cfg
      group: root
      owner: root
      mode: 0755

  - name: Install "yuglify" node.js package.
    npm:
      name: yuglify
      global: yes
