---
  - name: Install required system packages.
    apt:
      name: "{{ system_packages }}"
      state: present
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: safe
      update-cache: yes
      cache_valid_time: 43200

  - name: Install required Python packages.
    easy_install: name={{ item }}
    with_items: "{{ python_packages }}"

  - name: Install "yuglify" node.js package.
    npm:
      name: yuglify
      global: yes
