---
  - name: Install required system packages.
    apt:
      name: "{{ system_packages }}"
      state: present
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: safe
      update-cache: yes
      cache_valid_time: 43200

  - name: Install required Python packages.
    pip:
      name: "{{ python_packages }}"
      executable: pip3

  - name: Install s3cmd
    pip:
      name: s3cmd
    become: true
    become_user: root

  - name: Install .s3cfg file
    template:
      src: "files/conf/s3cfg"
      dest: /root/.s3cfg
      group: root
      owner: root
      mode: 0755

  - name: Upgrade NPM
    npm:
      name: npm
      global: true
      version: "6.14.11"
      state: latest

  - name: Install "yuglify" node.js package.
    npm:
      name: yuglify
      global: yes

  - name: Install CodeDeploy agent
    raw: cd /home/ubuntu && sudo wget https://aws-codedeploy-eu-west-2.s3.eu-west-2.amazonaws.com/latest/install && sudo chmod +x ./install && sudo ./install auto

  - name: Install Cloudwatch agent
    raw: mkdir /tmp/cloudwatch-logs && cd /tmp/cloudwatch-logs && wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb && sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

  - name: Install Cloudwatch config file
    template:
      src: "files/conf/cloudwatch.json"
      dest: /root/.cloudwatch.json
      group: root
      owner: root
      mode: 0644
